bool move_rel
bool depth_rel
bool heading_rel
int8 depth_ctrl
float32 roll_setpoint
float32 pitch_setpoint
float32 heading_setpoint
float32 depth_setpoint
float32 altitude_setpoint
float32 forward_setpoint
float32 sidemove_setpoint
float32 forward_tolerance
float32 sidemove_tolerance
float32 heading_tolerance
---
float32 roll_final
float32 pitch_final
float32 heading_final
float32 depth_final
float32 altitude_final
float32 forward_final
float32 sidemove_final
---
float32 roll_error
float32 pitch_error
float32 heading_error
float32 depth_error
float32 altitude_error
float32 forward_error
float32 sidemove_error
