float64 easting
float64 northing
float64 heading
float64 depth
float64 radius
bool is_circle
bool is_clockwise
---
float64 easting_final
float64 northing_final
float64 heading_final
---
float64 easting_error
float64 northing_error
float64 heading_error
