uint8 YAW_MODE_FACE_NEXT_WAYPOINT = 0
uint8 YAW_MODE_FACE_TARGET_FRAME = 1
uint8 YAW_MODE_SPECIFIED_HEADING = 2

string goal_id              # goal id to distinguish between identical goals, default is empty
string move_frame ""        # frame of forward/sidemove, default vehicle base_link
bool fixed_move true        # whether to monitor world->move_frame
string depth_frame ""       # default to move_frame, default vehicle base_link
bool fixed_depth true       # whether to monitor world->depth_frame
string heading_frame ""     # frame of heading roll_setpoints, default vehicle base_link
bool fixed_heading true     # whether to monitor world->heading_frame
string target_frame ""      # target frame to use for YAW_MODE_FACE_TARGET_FRAME

float32[] roll_setpoints
float32[] pitch_setpoints
float32[] heading_setpoints
float32[] depth_setpoints
float32[] forward_setpoints
float32[] sidemove_setpoints
uint8[] yaw_modes   # which yaw mode to use for particular setpoint

string global_planner_service ""
string local_planner_service ""
uint8 global_planner_period 10 # seconds
uint8 local_planner_period 5 # seconds
---
bool success
string message
---
PlannerFeedback feedback
