float32 turn_angle               # The desired angle of turn (degs), +ve cw, -ve ccw
float32 radius                   # In Metres from the origin
float32 tangent_offset           # Angle offset for facing direction relative to facing the centre, in degs, +ve cw, -ve ccw
float32 spiral_proportion        # 0 to 1. 0 = go out to radius first then encircle, 1 = move radially and angularly simultaneously (spiral).

---
string trajectory_id             # Returns a uuid if successful, otherwise, returns empty string
