<?xml version="1.0"?>
<package format="2">
  <name>bb_msgs</name>
  <version>0.2.3</version>
  <description>The bb_msgs package</description>

  <maintainer email="seowalex@u.nus.edu">Seow Alex</maintainer>

  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <depend>actionlib_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
</package>
