# Request
string[] input_child_frame_ids
string[] output_parent_frame_ids
string[] output_child_frame_ids
int32 clustering_duration 20
float64 tf_lookup_interval 0.05
int32 cache_size 100
int32 min_cluster_size 2
int32 min_samples 1
bool use_cache false # if true, use the cache with cache_size; otherwise, just collect as many transforms as possible in the given duration
bool persistent false # if true, then we use the same cache for (in parent, in child, out parent, out child) across multiple goals
---
# Result
geometry_msgs/TransformStamped[] clustered_transform
int32[] total_transforms_collected
int32[] transforms_in_cluster
---
# Feedback
float64[] collection_progress
int32[] transforms_collected_so_far
string current_status
