#### Request ####
# Target altitude above the current position in meters (positive up)
float32 altitude
float32 x_threshold         # Position threshold in x (meters)
float32 y_threshold         # Position threshold in y (meters)
float32 z_threshold         # Position threshold in z (meters)
---
#### Result ####
bb_uav_msgs/GoToResult result
---
#### Feedback ####
bb_uav_msgs/GoToFeedback feedback
