geometry_msgs/Vector3 center_pt  # XYZ in absolute position
float32 turn_angle               # The desired angle of turn (degs), +ve cw, -ve ccw
float32 standoff                # In Metres from the center Pt
float32 tangent_offset           # Angle offset for facing direction relative to facing the centre, in degs, +ve cw, -ve ccw
bool is_altitude_tracking         # If true, use altitude tracking
bool allow_ellipsoid_movement     # If true, moves in an ellipsoid, otherwise, move to the closest point on the arc before encircling the centroid.

---
int32 trajectory_id              # Returns a non-negative id if successful, otherwise, returns -1