# Service to register template in image matching pose estimator
# Grabs image and bounding box (optional) from topics and registers template
string template_name
string image_topic_name # compressed_image_topic
string detected_objects_topic_name
string object_name
float32 width
float32 height
---
bool success
string error_message
