geometry_msgs/Vector3[] positionPoses      # XYZ: Must be the same length as orientationRPY
geometry_msgs/Vector3[] orientationRPY     # RPY in degs. If absolute orientation, Yaw is (0 to 360) degs, otherwise, all are (-180 to 180) degs. Must be the same length as positionPoses
bool relativeXYPositionGoal  # Assume Roll and Pitch are zero. If True, position XY Poses are wrt base_link, otherwise, are wrt to world frame
bool relativeZPositionGoal   # Assume Roll and Pitch are zero. If True, position Z Poses are wrt base_link, otherwise, are wrt to world frame
bool relativeOrientationGoal # Assume Roll and Pitch are zero. If True, relativeOrientationGoal are wrt current heading, otherwise, are wrt to world frame. Mutually exclusive with specifiedHeading
bool setFasterLimits         # Faster velocity, acceleration and jerk limits
bool isAltitudeTracking      # If true, use altitude tracking
bool specifiedHeading        # If true, use heading references in orientationRPY, else, yaw is calculated from curve tangent. Mutually exclusive with relativeOrientationGoal

### relativeOrientationGoal mutually exclusive with specifiedHeading, behaviour undefined ###

---
int32 trajectoryId              # Returns a non-negative id if successful, otherwise, returns -1
