#
#  Enums only -- to be used with std_msgs/UInt64
#                         # CAN ids
uint8 SBC=1               # 1
uint8 LOGIC_BACKPLANE=2   # 2
uint8 MHPB=3              # 3
uint8 THRUSTER_BOARD=4    # 4
uint8 TELEM_BOARD=5       # 5
uint8 RC=6                # 6
uint8 POPB=7              # 17
uint8 ESC1=8              # 33
uint8 ESC2=9              # 34
uint8 BATTERY1=10         # 49
uint8 BATTERY2=11         # 50
uint8 ACTUATION_BOARD=12  # 65
uint8 NAV=13              # 81
