name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: ros:humble-ros-base
    steps:
      - run: sudo chown -R `whoami`:`whoami` .
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          path: src/bb_msgs
          branch: humble
      - name: Set up workspace
        run: |
          mkdir -p /tmp/ws/src;
          ln -s `pwd` /tmp/ws/src;
      - name: Build
        shell: bash
        run: |
          cd /tmp/ws;
          source /opt/ros/humble/setup.bash;
          colcon build --merge-install;
