name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, ros-noetic]
    steps:
      - name: Setup catkin workspace
        run: source /opt/ros/noetic/setup.bash && catkin init

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          path: src/bb_msgs

      - name: Install dependencies
        run: source /opt/ros/noetic/setup.bash && rosdep update && rosdep install --from-paths src -i -r -y

      - name: Build
        run: source /opt/ros/noetic/setup.bash && catkin build --no-status
